WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 900

PLAYER_SIZE = [40,40]
JUMPING_STRENGTH = 1350
GRAVITY = 1500

PLATFORM_SIZE = [WINDOW_WIDTH,100]
MOVEMENT_SPEED = 0.4
DASH_SPEED = 4

BACKGROUND_COLOR =  'teal'
PLAYER_COLOR =  'white'
PLATFORM_COLOR = 'brown'
RADIUS = min(PLAYER_SIZE[0], PLAYER_SIZE[1]) // 2